root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/app ./src/cmd/main.go"
bin = "tmp/app"
delay = 1000
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "docker"]
exclude_regex = ["_test.go"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
